fix(audio): swap non-phaser sounds to use capacitor audio
openforge/rock-the-steps-app pull request #83
Opened 2023-09-27 22:27 UTC by PaulPaulDevelops

# Pull request type

-   [X] Bugfix
-   [X] Feature
-   [ ] Code style update (formatting, renaming)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] Documentation content changes
-   [ ] E2E Test(s)
-   [ ] Other (please describe):

# What is the current behavior?
- After the success/fail sounds, all audio in the application would not work as expected.

# What is the new behavior?
Did some debugging and found that these specific sounds were not set by Phaser, but instead were HTMLAudioElements. I looked to see if we could keep these and add a pause call (in case the audio is still in the foreground after playing / navigating away), but that did not work in this case.

I migrated these audio sounds to use Capacitor Native Audio. I pre-loaded up the sounds in the world (where we do phaser loading) for consistency.
I renamed the two sound folders in our assets to be more specific on which sounds are set/used by phaser vs. what will be copied into the ios/android folders on cap sync/copy.

# Does this introduce a breaking change?

-   [ ] Yes
-   [X] No

# Other information

2023-09-27 23:24 UTC, Ricardo385 commented on libs/shared/phaser-singleton/src/lib/scenes/world.scene.ts
> +                assetId: 'fail',
Hey, could we have this `assetId` as a constant?

2023-09-27 23:25 UTC, Ricardo385 commented on libs/shared/phaser-singleton/src/lib/scenes/world.scene.ts
> +                assetId: 'success',
Same here, could we have this `assetId` as a constant?

2023-09-27 23:26 UTC, Ricardo385 requested changes
Nice and great work here! Just a minor comment

2023-09-29 19:26 UTC, PaulPaulDevelops commented
@Ricardo385 @emmanuelOpenForge thank you for the feedback! It has been resolved.

2023-10-03 14:27 UTC, Ricardo385 approved these changes

2023-10-03 14:27 UTC, merged